Redux in react components
MayPyone/Bookstore pull request #3
Opened 2023-09-05 20:59 UTC by MayPyone

-Displayed books
-Added event handlers for add and remove actions

2023-09-05 21:27 UTC, DammyShittu requested changes
Hi @MayPyone,

## Highlights
✔️ Book removal feature

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-05 21:27 UTC, DammyShittu commented on src/component/Form.js
> +}
- [ ] Your form component should be controlled. This means the value of the title and author should be set using a local state, not the user's direct input; and the value of the states should be using the `onChange` method. Kindly see [this article](https://blog.logrocket.com/controlled-vs-uncontrolled-components-in-react/) on how to make controlled components.

2023-09-05 21:27 UTC, DammyShittu commented on src/component/Book.js
> +    </li>
- [ ] The use of this component is for representing only ONE book. This `useSelector` should be used in the BookList component, and the mapping should be done in the BookList component, passing props to this Book component and rendering information for only one book.

2023-09-05 21:27 UTC, DammyShittu commented on src/component/BookList.js
> +}
- [ ] Kindly fetch the books from the store using `useSelector` and add the mapping here, instead of the Book component.

2023-09-06 06:49 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @MayPyone, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Implemented required changes. :heavy_check_mark: 
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-06 06:50 UTC, merged